import { useState, type DragEvent } from 'react';
import type { AssetKind } from '../../../shared/types';
import { useAppStore } from '../store';
import { Card, Empty, Page, Pill } from '../components/Ui';
import { projectMediaUrl } from '../media';
const KINDS:AssetKind[]=['character','location','prop','wardrobe','reference','keyframe','image','video','audio'];
export function Assets(){const{project,setProject,updateProject,setError}=useAppStore();const[kind,setKind]=useState<AssetKind>('reference');if(!project)return <Page title="Assets"><Empty>Open a project first.</Empty></Page>;const add=async()=>{try{const next=await window.cineforge.asset.import(kind);if(next)setProject(next);}catch(e){setError(e instanceof Error?e.message:String(e));}};
const drag=(event:DragEvent,assetId:string)=>{event.dataTransfer.effectAllowed='copy';event.dataTransfer.setData('application/x-cineforge-asset',assetId);};
return <Page title="Asset library" subtitle="Characters, locations and props are continuity entities. Drag any asset onto a shot in Storyboard or Shot Workshop." actions={<div className="row"><select value={kind} onChange={e=>setKind(e.target.value as AssetKind)}>{KINDS.map(k=><option key={k}>{k}</option>)}</select><button className="primary" onClick={add}>Import</button></div>}>{project.assets.length===0?<Empty>No assets yet. Import character sheets, locations, props, wardrobe or hero frames.</Empty>:<div className="asset-grid">{project.assets.map(asset=><div key={asset.id} className="asset-drag-wrap" draggable onDragStart={e=>drag(e,asset.id)}><Card className="asset-card">{['image','reference','keyframe','character','location','prop','wardrobe'].includes(asset.kind)?<img className="asset-preview" src={projectMediaUrl(asset.projectPath)} alt={asset.name}/>:asset.kind==='video'?<video className="asset-preview" src={projectMediaUrl(asset.projectPath)} muted controls preload="metadata"/>:<div className="asset-icon">♪</div>}<div className="asset-title-row"><Pill>{asset.kind}</Pill><small title={asset.projectPath}>{asset.projectPath}</small></div><label>Name<input value={asset.name} onChange={e=>updateProject(p=>{const a=p.assets.find(x=>x.id===asset.id);if(a)a.name=e.target.value;})}/></label><label>Continuity description<textarea className="asset-notes" value={asset.notes} onChange={e=>updateProject(p=>{const a=p.assets.find(x=>x.id===asset.id);if(a)a.notes=e.target.value;})} placeholder="Face, hair, clothing, material, colors, distinguishing marks, spatial rules…"/></label><label>Tags<input value={asset.tags.join(', ')} onChange={e=>updateProject(p=>{const a=p.assets.find(x=>x.id===asset.id);if(a)a.tags=e.target.value.split(',').map(x=>x.trim()).filter(Boolean);})} placeholder="hero, wet, night"/></label></Card></div>)}</div>}</Page>;}
