import { useState } from 'react';
import type { CapCutHandoffResult } from '../../../shared/api';
import { useAppStore } from '../store';
import { Card, Empty, Page, Pill } from '../components/Ui';
export function Finishing(){const{project,setError,setNotice}=useAppStore();const[result,setResult]=useState<CapCutHandoffResult>();const[busy,setBusy]=useState(false);if(!project)return <Page title="CapCut finishing"><Empty>Open a project first.</Empty></Page>;
const prepare=async()=>{try{setBusy(true);await useAppStore.getState().persist();const handoff=await window.cineforge.capcut.prepareHandoff();setResult(handoff);setNotice('CapCut × Codex handoff prepared. The canonical CineForge project remains unchanged.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
const copyPrompt=async()=>{if(!result)return;await navigator.clipboard.writeText(result.prompt);setNotice('CapCut × Codex instruction copied.');};
return <Page title="CapCut finishing" subtitle="Generate a deterministic handoff for the official CapCut × Codex workflow while keeping CineForge as the canonical project state." actions={<button className="primary" onClick={prepare} disabled={busy||project.timeline.length===0}>{busy?'Preparing…':'Prepare CapCut handoff'}</button>}>
<div className="grid two"><Card title="Cost wall" kicker="RECURRING PAID SERVICES"><div className="status-list"><div><span>Codex / ChatGPT</span><Pill>Allowed</Pill></div><div><span>{project.settings.capcut.pro?'CapCut Pro':'CapCut'}</span><Pill>Allowed</Pill></div><div><span>CapCut AI credits</span><Pill>{project.settings.costPolicy.allowCapcutAiCredits?'Allowed':'Disabled'}</Pill></div><div><span>Cloud AI generation APIs</span><Pill>Blocked by design</Pill></div></div><p className="muted">ASR, TTS, image/video generation, upscale, interpolation and QC are expected to run locally. CapCut is used for editorial and finishing unless you explicitly opt into AI credits.</p></Card>
<Card title="Handoff contents" kicker="EDITABLE DRAFT"><div className="rules"><p><b>Timeline.</b> Clip order, trims, volumes and source media paths are written to the manifest.</p><p><b>Intent.</b> Dialogue and continuity notes travel with each shot.</p><p><b>Finishing.</b> Codex is instructed to use CapCut for captions, typography, transitions, tracking/reframe, effects and polish.</p><p><b>Safety.</b> Replacement cloud generation is prohibited unless the project explicitly allows CapCut AI credits.</p></div></Card></div>
{project.timeline.length===0&&<Card title="Timeline required" kicker="NOT READY"><p className="muted">Build the latest cut in Timeline first. The CapCut handoff represents the current canonical CineForge timeline.</p></Card>}
{result&&<Card title="Handoff ready" kicker="CAPCUT × CODEX" actions={<div className="row"><button className="ghost" onClick={copyPrompt}>Copy instruction</button><button className="ghost" onClick={()=>window.cineforge.system.reveal(result.taskPath)}>Reveal files</button></div>}><div className="status-list"><div><span>Directory</span><code>{result.directory}</code></div><div><span>Manifest</span><code>{result.manifestPath}</code></div><div><span>Task</span><code>{result.taskPath}</code></div></div><label>Codex instruction<textarea className="short" value={result.prompt} readOnly /></label><p className="muted">Open the official CapCut × Codex workflow, point Codex at the generated task/manifest, and keep the resulting CapCut project editable for final verification.</p></Card>}
</Page>;}
