import { useEffect, useState } from 'react';
import { useAppStore } from '../store';
import { Card, Empty, Page, Pill } from '../components/Ui';
const PAGE_SIZE=50;
export function Queue(){
  const{project,queue,setQueue,setError}=useAppStore();const[page,setPage]=useState(0);
  useEffect(()=>{void window.cineforge.render.snapshot().then(setQueue);},[setQueue]);
  if(!project)return <Page title="Render queue"><Empty>Open a project first.</Empty></Page>;
  const cancel=async(id:string)=>{try{setQueue(await window.cineforge.render.cancel(id));}catch(e){setError(e instanceof Error?e.message:String(e));}};
  const retry=async(id:string)=>{try{setQueue(await window.cineforge.render.retry(id));}catch(e){setError(e instanceof Error?e.message:String(e));}};
  const newest=[...queue.jobs],pages=Math.max(1,Math.ceil(newest.length/PAGE_SIZE)),safePage=Math.min(page,pages-1),visible=newest.slice(safePage*PAGE_SIZE,(safePage+1)*PAGE_SIZE);
  return <Page title="Render queue" subtitle="Durable single-GPU queue. Newest jobs appear first; history is paged so long-running projects remain responsive.">
    {queue.jobs.length===0?<Empty>No renders queued yet.</Empty>:<><div className="job-stack">{visible.map(job=>{const shot=project.shots.find(s=>s.id===job.shotId);return <Card key={job.id} title={shot?.title||job.shotId} kicker={job.modelFamily} actions={<Pill>{job.status}</Pill>}><div className="progress"><span style={{width:`${Math.round(job.progress*100)}%`}} /></div><div className="job-meta"><span>{job.message}</span><span>{Math.round(job.progress*100)}%</span></div>{job.spec&&<small className="muted">Frozen at {new Date(job.spec.queuedProjectUpdatedAt).toLocaleString()} · seed {job.spec.shot.generation.seed} · {job.spec.workflowProfile.name}{job.spec.workflowSha256?` · wf ${job.spec.workflowSha256.slice(0,10)}`:''}</small>}{job.error&&<pre className="error-box">{job.error}</pre>}<div className="row">{['queued','preparing','uploading','submitted','running','recovering','stalled','downloading'].includes(job.status)&&<button className="danger ghost" disabled={job.status==='recovering'&&queue.runningJobId!==job.id} title={job.status==='recovering'&&queue.runningJobId!==job.id?'Waiting for this backend identity to become the active serialized recovery job before safe cancellation.':undefined} onClick={()=>cancel(job.id)}>Cancel</button>}{['failed','cancelled','done','orphaned'].includes(job.status)&&<button className="ghost" onClick={()=>retry(job.id)}>{job.status==='done'?'Render exact snapshot':job.spec?'Retry exact snapshot':'Retry legacy job'}</button>}</div>{job.outputs.length>0&&<div className="output-list">{job.outputs.map(o=><div key={o.id}><Pill>{o.mediaType}</Pill><span>{o.filename}{o.technicalQc&&!o.technicalQc.passed?` · QC: ${o.technicalQc.issues.join('; ')}`:o.technicalQc?.warnings?.length?` · QC pass · warnings: ${o.technicalQc.warnings.join('; ')}`:o.technicalQc?' · QC pass':''}</span><button className="mini" onClick={()=>window.cineforge.system.reveal(o.path)}>↗</button></div>)}</div>}</Card>;})}</div>{pages>1&&<div className="row pagination"><button className="ghost" disabled={safePage===0} onClick={()=>setPage(value=>Math.max(0,value-1))}>← Newer</button><span className="muted">Page {safePage+1} / {pages} · {queue.jobs.length} jobs</span><button className="ghost" disabled={safePage>=pages-1} onClick={()=>setPage(value=>Math.min(pages-1,value+1))}>Older →</button></div>}</>}
  </Page>;
}
