import { useMemo, useState } from 'react';
import type { GenerationMode, ModelFamily, RuntimeBackend, WorkflowBinding, WorkflowBindingKey, WorkflowProfile, WorkflowPurpose } from '../../../shared/types';
import { useAppStore } from '../store';
import { Card, Empty, Page, Pill } from '../components/Ui';

const FAMILIES: ModelFamily[] = ['ltx-2.5-fast','ltx-2.3','hunyuan-video-1.5','wan-2.2-5b','framepack','custom'];
const MODES: GenerationMode[] = ['t2v','i2v','flf2v','ia2v','v2v','t2i','i2i'];
const PURPOSES: WorkflowPurpose[] = ['video','image','audio','utility'];
const BINDING_KEYS: WorkflowBindingKey[] = ['prompt','negativePrompt','width','height','frames','fps','steps','cfg','seed','startImage','endImage','locationImage','characterImage1','characterImage2','characterImage3','characterImage4','propImage1','propImage2','referenceImage1','referenceImage2','referenceImage3','referenceImage4','inputAudio','inputVideo','filenamePrefix'];

export function Settings() {
  const { project, updateProject, setError, setNotice } = useAppStore();
  const [family,setFamily]=useState<ModelFamily>('ltx-2.5-fast');
  const [mode,setMode]=useState<GenerationMode>('i2v');
  const [purpose,setPurpose]=useState<WorkflowPurpose>('video');
  const [selectedProfileId,setSelectedProfileId]=useState<string>();
  const [newKey,setNewKey]=useState<WorkflowBindingKey>('prompt');
  const [newNodeId,setNewNodeId]=useState(''); const [newClassType,setNewClassType]=useState(''); const [newInput,setNewInput]=useState(''); const [newJsonPath,setNewJsonPath]=useState('');
  const selected=useMemo(()=>project?.settings.workflowProfiles.find(p=>p.id===selectedProfileId),[project,selectedProfileId]);
  if(!project)return <Page title="Settings"><Empty>Open a project first.</Empty></Page>;

  const testComfy=async()=>{try{const r=await window.cineforge.system.pingComfy(project.settings.comfyUrl);setNotice(r.reachable?'ComfyUI connected.':`ComfyUI offline: ${r.error}`);}catch(e){setError(e instanceof Error?e.message:String(e));}};
  const importProfile=async(runtime:RuntimeBackend)=>{try{const r=runtime==='wangp'?await window.cineforge.workflow.importWanGp():await window.cineforge.workflow.importComfy();if(!r)return;if(r.format==='ui'){setError(r.warnings?.join('\n')||'ComfyUI must be running to convert this UI workflow. Export API Format for complex/subgraph workflows.');return;}const profile:WorkflowProfile={id:crypto.randomUUID(),runtime,name:`${runtime==='wangp'?'WanGP':'ComfyUI'} · ${family} ${mode}`,purpose,modelFamily:family,mode,workflowPath:r.path,workflowFormat:r.format,bindings:r.suggestedBindings,enabled:true,notes:runtime==='wangp'?'Imported from a WanGP-exported settings JSON. Review inferred JSON-path bindings before production renders.':'Imported from ComfyUI. Review inferred node/input bindings before production renders.'};updateProject(p=>p.settings.workflowProfiles.push(profile));setSelectedProfileId(profile.id);setNotice(`Imported ${profile.name} with ${profile.bindings.length} inferred bindings.${r.warnings?.length?` ${r.warnings.length} warning(s).`:''}`);}catch(e){setError(e instanceof Error?e.message:String(e));}};
  const updateProfile=(id:string,fn:(p:WorkflowProfile)=>void)=>updateProject(p=>{const profile=p.settings.workflowProfiles.find(w=>w.id===id);if(profile)fn(profile);});
  const addBinding=()=>{if(!selected)return;const runtime=selected.runtime??(selected.workflowFormat==='wangp-settings'?'wangp':'comfyui');let binding:WorkflowBinding;if(runtime==='wangp'){if(!newJsonPath.trim())return;binding={key:newKey,jsonPath:newJsonPath.trim(),required:false};setNewJsonPath('');}else{if(!newInput.trim()||(!newNodeId.trim()&&!newClassType.trim()))return;binding={key:newKey,selector:{...(newNodeId.trim()?{nodeId:newNodeId.trim()}:{}),...(newClassType.trim()?{classType:newClassType.trim()}:{})},input:newInput.trim(),required:false};setNewNodeId('');setNewClassType('');setNewInput('');}updateProfile(selected.id,p=>p.bindings.push(binding));};
  const selectedRuntime:RuntimeBackend|undefined=selected?(selected.runtime??(selected.workflowFormat==='wangp-settings'?'wangp':'comfyui')):undefined;

  return <Page title="Pipeline settings" subtitle="Production is WanGP-first. ComfyUI stays available as a local lab/fallback; recurring paid services are intentionally limited to Codex/ChatGPT + CapCut.">
    <div className="grid two">
      <Card title="Cost policy" kicker="CODEX + CAPCUT ONLY">
        <label>Policy<input value="Recurring paid services: Codex/ChatGPT + CapCut" readOnly /></label>
        <label className="check"><input type="checkbox" checked={project.settings.localOnly} onChange={e=>updateProject(p=>p.settings.localOnly=e.target.checked)} />Block non-loopback AI endpoints</label>
        <label className="check"><input type="checkbox" checked={project.settings.capcut.pro} onChange={e=>updateProject(p=>p.settings.capcut.pro=e.target.checked)} />CapCut Pro available</label>
        <label className="check"><input type="checkbox" checked={project.settings.costPolicy.allowCapcutAiCredits} onChange={e=>updateProject(p=>p.settings.costPolicy.allowCapcutAiCredits=e.target.checked)} />Allow CapCut AI credits <b>(off recommended)</b></label>
        <p className="muted">With AI credits disabled, CapCut is the editor/finishing room: timeline, captions, typography, effects, transitions, tracking/reframe and final polish. Generation stays local.</p>
      </Card>
      <Card title="WanGP production backend" kicker="LOCAL GENERATION">
        <label>WanGP root<input value={project.settings.wangp.rootPath} onChange={e=>updateProject(p=>p.settings.wangp.rootPath=e.target.value)} placeholder="D:\Wan2GP or /opt/Wan2GP" /></label>
        <div className="form-grid two-col"><label>Python<input value={project.settings.wangp.pythonPath} onChange={e=>updateProject(p=>p.settings.wangp.pythonPath=e.target.value)} /></label><label>Entrypoint<input value={project.settings.wangp.entrypoint} onChange={e=>updateProject(p=>p.settings.wangp.entrypoint=e.target.value)} /></label></div>
        <div className="form-grid three-col"><label>Profile<select value={project.settings.wangp.profile} onChange={e=>updateProject(p=>p.settings.wangp.profile=Number(e.target.value) as 1|2|3|4|5)}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x}{x===4?' · recommended':''}</option>)}</select></label><label>Attention<select value={project.settings.wangp.attention} onChange={e=>updateProject(p=>p.settings.wangp.attention=e.target.value as 'auto'|'sdpa'|'flash'|'sage'|'sage2')}><option value="auto">auto</option><option value="sdpa">sdpa</option><option value="flash">flash</option><option value="sage">sage</option><option value="sage2">sage2</option></select></label><label className="check"><input type="checkbox" checked={project.settings.wangp.dryRunBeforeRender} onChange={e=>updateProject(p=>p.settings.wangp.dryRunBeforeRender=e.target.checked)} />Dry-run first</label></div>
      </Card>
    </div>
    <div className="grid two"><Card title="ComfyUI lab / fallback" kicker="LOCAL R&D"><label>Base URL<input value={project.settings.comfyUrl} onChange={e=>updateProject(p=>p.settings.comfyUrl=e.target.value)} /></label><label>ComfyUI input directory<input value={project.settings.comfyInputDir} onChange={e=>updateProject(p=>p.settings.comfyInputDir=e.target.value)} /></label><button className="ghost" onClick={testComfy}>Test ComfyUI</button></Card><Card title="Editing / export" kicker="DETERMINISTIC"><label>FFmpeg command / path<input value={project.settings.ffmpegPath} onChange={e=>updateProject(p=>p.settings.ffmpegPath=e.target.value)} /></label><div className="form-grid two-col"><label>Master container<select value={project.settings.outputContainer} onChange={e=>updateProject(p=>p.settings.outputContainer=e.target.value as 'mp4'|'mov'|'webm')}><option>mp4</option><option>mov</option><option>webm</option></select></label><label>Default FPS<input type="number" min="1" max="120" value={project.settings.defaultFps} onChange={e=>updateProject(p=>p.settings.defaultFps=Math.max(1,Number(e.target.value)||24))} /></label></div><label>CapCut handoff folder<input value={project.settings.capcut.handoffDirName} onChange={e=>updateProject(p=>p.settings.capcut.handoffDirName=e.target.value)} /></label></Card></div>
    <Card title="Import generation profile" kicker="VERSION-SAFE PRESETS"><div className="form-grid three-col"><label>Purpose<select value={purpose} onChange={e=>setPurpose(e.target.value as WorkflowPurpose)}>{PURPOSES.map(x=><option key={x}>{x}</option>)}</select></label><label>Family<select value={family} onChange={e=>setFamily(e.target.value as ModelFamily)}>{FAMILIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value as GenerationMode)}>{MODES.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="row"><button className="primary" onClick={()=>importProfile('wangp')}>Import WanGP settings</button><button className="ghost" onClick={()=>importProfile('comfyui')}>Import ComfyUI workflow</button></div></Card>
    <Card title="Local AI Director" kicker="OPENAI-COMPATIBLE LOCAL LLM"><div className="form-grid three-col"><label>Base URL<input value={project.settings.director.baseUrl} onChange={e=>updateProject(p=>p.settings.director.baseUrl=e.target.value)} /></label><label>Model<input value={project.settings.director.model} onChange={e=>updateProject(p=>p.settings.director.model=e.target.value)} /></label><label>Temperature<input type="number" min="0" max="2" step="0.1" value={project.settings.director.temperature} onChange={e=>updateProject(p=>p.settings.director.temperature=Number(e.target.value))} /></label></div></Card>
    <Card title="Workflow profiles" kicker="ROUTING TABLE"><div className="profiles">{project.settings.workflowProfiles.map(profile=>{const runtime=profile.runtime??(profile.workflowFormat==='wangp-settings'?'wangp':'comfyui');return <button key={profile.id} className={`profile-row profile-button ${selectedProfileId===profile.id?'selected':''}`} onClick={()=>setSelectedProfileId(profile.id)}><span className={`toggle-dot ${profile.enabled?'on':''}`} /><div><strong>{profile.name}</strong><small>{runtime} · {profile.purpose??'video'} · {profile.modelFamily} · {profile.mode}</small></div><Pill>{profile.bindings.length} bindings</Pill><code>{profile.workflowPath||'not configured'}</code></button>;})}</div></Card>
    {selected&&<Card title={`Profile · ${selected.name}`} kicker={`${selectedRuntime?.toUpperCase()} BINDING EDITOR`} actions={<div className="row"><label className="inline-check"><input type="checkbox" checked={selected.enabled} onChange={e=>updateProfile(selected.id,p=>p.enabled=e.target.checked)} />Enabled</label>{!selected.id.startsWith('builtin-')&&<button className="ghost danger" onClick={()=>{updateProject(p=>p.settings.workflowProfiles=p.settings.workflowProfiles.filter(x=>x.id!==selected.id));setSelectedProfileId(undefined);}}>Delete</button>}</div>}>
      <div className="form-grid four-col"><label>Name<input value={selected.name} onChange={e=>updateProfile(selected.id,p=>p.name=e.target.value)} /></label><label>Purpose<select value={selected.purpose??'video'} onChange={e=>updateProfile(selected.id,p=>p.purpose=e.target.value as WorkflowPurpose)}>{PURPOSES.map(x=><option key={x}>{x}</option>)}</select></label><label>Family<select value={selected.modelFamily} onChange={e=>updateProfile(selected.id,p=>p.modelFamily=e.target.value as ModelFamily)}>{FAMILIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Mode<select value={selected.mode} onChange={e=>updateProfile(selected.id,p=>p.mode=e.target.value as GenerationMode)}>{MODES.map(x=><option key={x}>{x}</option>)}</select></label></div>
      <label>Workflow/settings path<input value={selected.workflowPath} readOnly /></label><label>Notes<textarea className="short" value={selected.notes||''} onChange={e=>updateProfile(selected.id,p=>p.notes=e.target.value)} /></label>
      {selectedRuntime==='wangp'?<><div className="binding-table"><div className="binding-row binding-head"><b>Value</b><b>JSON path</b><b>Transform</b><b>Required</b><b /></div>{selected.bindings.map((binding,i)=><div className="binding-row" key={`${binding.key}-${i}`}><code>{binding.key}</code><code>{binding.jsonPath||'—'}</code><span>{binding.transform||'identity'}</span><input type="checkbox" checked={Boolean(binding.required)} onChange={e=>updateProfile(selected.id,p=>p.bindings[i].required=e.target.checked)} /><button className="mini danger" onClick={()=>updateProfile(selected.id,p=>p.bindings.splice(i,1))}>×</button></div>)}</div><div className="binding-add"><select value={newKey} onChange={e=>setNewKey(e.target.value as WorkflowBindingKey)}>{BINDING_KEYS.map(k=><option key={k}>{k}</option>)}</select><input value={newJsonPath} onChange={e=>setNewJsonPath(e.target.value)} /><button className="ghost" onClick={addBinding}>Add binding</button></div></>:<><div className="binding-table"><div className="binding-row binding-head"><b>Value</b><b>Node</b><b>Input</b><b>Required</b><b /></div>{selected.bindings.map((binding,i)=><div className="binding-row" key={`${binding.key}-${i}`}><code>{binding.key}</code><span>{binding.selector?.nodeId||binding.selector?.classType||binding.selector?.titleIncludes||'—'}</span><code>{binding.input||'—'}</code><input type="checkbox" checked={Boolean(binding.required)} onChange={e=>updateProfile(selected.id,p=>p.bindings[i].required=e.target.checked)} /><button className="mini danger" onClick={()=>updateProfile(selected.id,p=>p.bindings.splice(i,1))}>×</button></div>)}</div><div className="binding-add"><select value={newKey} onChange={e=>setNewKey(e.target.value as WorkflowBindingKey)}>{BINDING_KEYS.map(k=><option key={k}>{k}</option>)}</select><input placeholder="node id" value={newNodeId} onChange={e=>setNewNodeId(e.target.value)} /><input placeholder="class type" value={newClassType} onChange={e=>setNewClassType(e.target.value)} /><input placeholder="input name" value={newInput} onChange={e=>setNewInput(e.target.value)} /><button className="ghost" onClick={addBinding}>Add binding</button></div></>}
    </Card>}
  </Page>;
}
