import { useState, type DragEvent, type ReactNode } from 'react';
import { MODEL_DEFAULTS } from '../../../shared/defaults';
import { chooseModelForShot } from '../../../shared/routing';
import type { Asset, ContinuityReview, GenerationMode, ModelFamily, QualityIntent, Shot } from '../../../shared/types';
import { continuityReviewInputKey } from '../../../shared/director-signature';
import { useAppStore } from '../store';
import { Card, Empty, Page, Pill } from '../components/Ui';
import { projectMediaUrl } from '../media';
import { alternateShotTitle, appendProjectText, isStudioWorkflowReady, resolveStudioWorkflow, studioWorkflowIssue } from '../studio-logic';
import { takeUseConfirmationMessage } from '../../../shared/take-policy';
import { continuityFrameForShot, rebuildDefaultSequentialDependencies } from '../../../shared/production-state';

const MODELS: ModelFamily[] = ['ltx-2.5-fast','ltx-2.3','hunyuan-video-1.5','wan-2.2-5b','framepack','custom'];
const MODES: GenerationMode[] = ['t2v','i2v','flf2v','ia2v','v2v'];
const QUALITIES: QualityIntent[] = ['preview','balanced','hero'];

export function Shots(){
  const{project,selectedShotId,selectShot,updateProject,setError,setNotice,setQueue,setView,setProject,setBusy}=useAppStore();
  const[keyframeProfileId,setKeyframeProfileId]=useState('');const[keyframeBusy,setKeyframeBusy]=useState<'start'|'end'|null>(null);const[continuityBusy,setContinuityBusy]=useState(false);const[continuityReview,setContinuityReview]=useState<ContinuityReview>();
  if(!project)return <Page title="Shots"><Empty>Open a project first.</Empty></Page>;
  const sorted=[...project.shots].sort((a,b)=>{const sa=project.scenes.find(s=>s.id===a.sceneId)?.index||0;const sb=project.scenes.find(s=>s.id===b.sceneId)?.index||0;return sa-sb||a.index-b.index;});
  const selected=project.shots.find(s=>s.id===selectedShotId)||sorted[0];const selectedOrder=selected?sorted.findIndex(s=>s.id===selected.id):-1;const previousCandidate=selectedOrder>0?sorted[selectedOrder-1]:undefined;const nextCandidate=selectedOrder>=0&&selectedOrder<sorted.length-1?sorted[selectedOrder+1]:undefined;const previousShot=previousCandidate?.sceneId===selected?.sceneId?previousCandidate:undefined;const nextShot=nextCandidate?.sceneId===selected?.sceneId?nextCandidate:undefined;
  const imageProfiles=project.settings.workflowProfiles.filter(p=>p.enabled&&(p.purpose??'video')==='image'&&p.workflowPath&&p.validation?.structuralStatus==='valid');const activeKeyframeProfileId=imageProfiles.some(p=>p.id===keyframeProfileId)?keyframeProfileId:(imageProfiles[0]?.id||'');
  const mutate=(fn:(shot:Shot)=>void)=>selected&&updateProject(p=>{const s=p.shots.find(x=>x.id===selected.id);if(s)fn(s);});
  const moveWithinScene=(delta:number)=>{if(!selected)return;updateProject(p=>{const siblings=p.shots.filter(s=>s.sceneId===selected.sceneId).sort((a,b)=>a.index-b.index);const index=siblings.findIndex(s=>s.id===selected.id);const target=index+delta;if(index<0||target<0||target>=siblings.length)return;const a=siblings[index],b=siblings[target];[a.index,b.index]=[b.index,a.index];const scene=p.scenes.find(s=>s.id===selected.sceneId);if(scene)scene.shotIds=[...siblings].sort((x,y)=>x.index-y.index).map(s=>s.id);rebuildDefaultSequentialDependencies(p,[selected.sceneId]);});};
  const duplicateShot=()=>{if(!selected)return;if(project.shots.length>=100_000){setError('Duplicating this shot would exceed the 100000-shot project safety limit.');return;}const duplicateId=crypto.randomUUID();updateProject(p=>{const source=p.shots.find(s=>s.id===selected.id);if(!source)return;const siblings=p.shots.filter(s=>s.sceneId===source.sceneId).sort((a,b)=>a.index-b.index),sourcePosition=siblings.findIndex(s=>s.id===source.id);if(sourcePosition<0)return;const copy=structuredClone(source);copy.id=duplicateId;copy.title=alternateShotTitle(source.title);copy.status='draft';copy.latestRenderId=undefined;copy.latestAttemptRenderId=undefined;copy.canonicalRenderId=undefined;copy.plannedStartStateId=undefined;copy.plannedEndStateId=undefined;copy.actualStartStateId=undefined;copy.observedFinalStateId=undefined;copy.generation.seed=Math.floor(Math.random()*2147483647);siblings.splice(sourcePosition+1,0,copy);siblings.forEach((shot,index)=>shot.index=index+1);p.shots.push(copy);const scene=p.scenes.find(s=>s.id===source.sceneId);if(scene)scene.shotIds=siblings.map(s=>s.id);rebuildDefaultSequentialDependencies(p,[source.sceneId]);});selectShot(duplicateId);setNotice(`Duplicated ${selected.title} as a fresh alternate with a new seed.`);};
  const deleteShot=()=>{if(!selected)return;const active=useAppStore.getState().queue.jobs.some(job=>job.shotId===selected.id&&['queued','preparing','uploading','submitted','running','recovering','stalled','downloading'].includes(job.status));if(active){setError('Cancel the active render for this shot before deleting it.');return;}if(!window.confirm(`Delete “${selected.title}” from the shot plan and timeline? Existing render files remain on disk, but their project associations will be removed.`))return;const fallback=sorted[selectedOrder+1]??sorted[selectedOrder-1];updateProject(p=>{p.shots=p.shots.filter(shot=>shot.id!==selected.id);p.timeline=p.timeline.filter(clip=>clip.shotId!==selected.id);const siblings=p.shots.filter(shot=>shot.sceneId===selected.sceneId).sort((a,b)=>a.index-b.index);siblings.forEach((shot,index)=>shot.index=index+1);const scene=p.scenes.find(item=>item.id===selected.sceneId);if(scene)scene.shotIds=siblings.map(shot=>shot.id);rebuildDefaultSequentialDependencies(p,[selected.sceneId]);});selectShot(fallback?.id);setNotice(`Deleted shot: ${selected.title}`);};
  const changeModel=(modelFamily:ModelFamily)=>mutate(s=>{const current=s.generation;const d=MODEL_DEFAULTS[modelFamily];s.generation={...current,...d,modelFamily,seed:current.seed,negativePrompt:current.negativePrompt,quality:current.quality,workflowProfileId:undefined};});
  const autoRoute=()=>{if(!selected)return;const validatedModels=[...new Set(project.settings.workflowProfiles.filter(profile=>profile.enabled&&(profile.purpose??'video')==='video'&&profile.workflowPath&&profile.validation?.structuralStatus==='valid').map(profile=>profile.modelFamily))];changeModel(chooseModelForShot(selected,{validatedModels}));};
  const reviewContinuity=async()=>{if(!selected)return;try{setContinuityBusy(true);setBusy(true);await useAppStore.getState().persist();const before=useAppStore.getState().project,currentShot=before?.shots.find(item=>item.id===selected.id);if(!before||!currentShot)throw new Error('Shot not found.');const signature=continuityReviewInputKey(before,currentShot),review=await window.cineforge.director.reviewShot(selected.id);const after=useAppStore.getState().project,afterShot=after?.shots.find(item=>item.id===selected.id);if(!after||!afterShot||continuityReviewInputKey(after,afterShot)!==signature){setContinuityReview(undefined);setNotice('Continuity review was discarded because the shot, previous shot, scene, or attached asset metadata changed while reviewing.');return;}setContinuityReview(review);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setContinuityBusy(false);setBusy(false);}};
  const queue=async()=>{if(!selected)return;try{await useAppStore.getState().persist();const snapshot=await window.cineforge.render.enqueue({projectRoot:project.rootPath,shotId:selected.id});setQueue(snapshot);setView('queue');}catch(e){setError(e instanceof Error?e.message:String(e));}};
  const generateKeyframe=async(role:'start'|'end')=>{if(!selected||!activeKeyframeProfileId){setError('Import and enable an image workflow profile in Settings first.');return;}try{setKeyframeBusy(role);setBusy(true);await useAppStore.getState().runProjectMutation(async()=>{await useAppStore.getState().persist();const next=await window.cineforge.keyframe.generate({projectRoot:project.rootPath,shotId:selected.id,role,workflowProfileId:activeKeyframeProfileId});setProject(next);setNotice(`${role==='start'?'Start':'End'} keyframe generated and attached to ${selected.title}.`);});}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setKeyframeBusy(null);setBusy(false);}};
  const cancelKeyframe=async()=>{try{if(await window.cineforge.keyframe.cancel())setNotice('Keyframe cancellation requested. The local runtime is stopping…');}catch(e){setError(e instanceof Error?e.message:String(e));}};

  const chainPreviousEnd=()=>{
    if(!selected||!previousShot){setError('There is no previous shot in this scene.');return;}
    const source=continuityFrameForShot(project,previousShot);if(!source){setError('The previous shot has neither an observed final frame nor a planned end keyframe.');return;}
    if(source.source==='planned-end'&&!window.confirm(`${previousShot.title} has no observed generated final frame yet. Use its planned end keyframe as a provisional start reference for ${selected.title}?`))return;
    mutate(s=>{s.startFrameAssetId=source.assetId;});
    setNotice(source.source==='observed-final'
      ?`Chained ${previousShot.title} observed final frame → ${selected.title} start frame.`
      :`Chained ${previousShot.title} planned end keyframe → ${selected.title} as a provisional start reference.`);
  };
  const propagateEnd=()=>{
    if(!selected||!nextShot){setError(!nextShot?'There is no next shot in this scene.':'Select a shot first.');return;}
    const source=continuityFrameForShot(project,selected);if(!source){setError('This shot has neither an observed final frame nor a planned end keyframe.');return;}
    if(!source.actual&&!window.confirm(`${selected.title} has no observed generated final frame yet. Use its planned end keyframe as a provisional start reference for ${nextShot.title}?`))return;
    updateProject(p=>{const next=p.shots.find(s=>s.id===nextShot.id);if(next)next.startFrameAssetId=source.assetId;});
    setNotice(source.actual
      ?`Chained ${selected.title} observed final frame → ${nextShot.title} start frame.`
      :`Chained ${selected.title} planned end keyframe → ${nextShot.title} as a provisional start reference.`);
  };
  const dropAsset=(event:DragEvent<HTMLElement>,slot:'character'|'location'|'reference'|'prop'|'start'|'end'|'video'|'audio')=>{
    event.preventDefault();if(!selected)return;
    const assetId=event.dataTransfer.getData('application/x-cineforge-asset');const asset=project.assets.find(a=>a.id===assetId);if(!asset)return;
    const allowed=slot==='character'?asset.kind==='character':
      slot==='location'?asset.kind==='location':
      slot==='reference'?asset.kind==='reference':
      slot==='prop'?['prop','wardrobe'].includes(asset.kind):
      slot==='start'?['image','reference','keyframe','character','location'].includes(asset.kind):
      slot==='end'?['image','reference','keyframe'].includes(asset.kind):
      slot==='video'?asset.kind==='video':asset.kind==='audio';
    if(!allowed){setError(`${asset.name} (${asset.kind}) cannot be dropped into ${slot}.`);return;}
    if(slot==='character'&&!selected.characterAssetIds.includes(asset.id)&&selected.characterAssetIds.length>=4){setError('This shot already has the maximum of 4 character references.');return;}
    if(slot==='reference'&&!(selected.referenceAssetIds??[]).includes(asset.id)&&(selected.referenceAssetIds?.length??0)>=4){setError('This shot already has the maximum of 4 generic visual references.');return;}
    if(slot==='prop'&&!selected.propAssetIds.includes(asset.id)&&selected.propAssetIds.length>=2){setError('This shot already has the maximum of 2 prop / wardrobe references.');return;}
    mutate(s=>{
      if(slot==='character'&&!s.characterAssetIds.includes(asset.id))s.characterAssetIds.push(asset.id);
      else if(slot==='location')s.locationAssetId=asset.id;
      else if(slot==='reference'){const refs=s.referenceAssetIds??(s.referenceAssetIds=[]);if(!refs.includes(asset.id))refs.push(asset.id);}
      else if(slot==='prop'&&!s.propAssetIds.includes(asset.id))s.propAssetIds.push(asset.id);
      else if(slot==='start')s.startFrameAssetId=asset.id;
      else if(slot==='end')s.endFrameAssetId=asset.id;
      else if(slot==='video')s.referenceVideoAssetId=asset.id;
      else if(slot==='audio')s.audioAssetId=asset.id;
      if(s.status==='draft')s.status='ready';
    });
    setNotice(`${asset.name} assigned to ${slot}.`);
  };
  const route=selected?resolveStudioWorkflow(project.settings.workflowProfiles,selected):undefined;const routeReady=Boolean(selected&&isStudioWorkflowReady(route,selected));const routeIssue=selected?studioWorkflowIssue(route,selected):undefined;
  const startAsset=selected?.startFrameAssetId?project.assets.find(a=>a.id===selected.startFrameAssetId):undefined;const endAsset=selected?.endFrameAssetId?project.assets.find(a=>a.id===selected.endFrameAssetId):undefined;const latest=selected?.latestRenderId?project.renderOutputs.find(o=>o.id===selected.latestRenderId):undefined;const takes=selected?[...project.renderOutputs].filter(o=>o.shotId===selected.id&&o.mediaType==='video').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)):[];const matchingProfiles=selected?project.settings.workflowProfiles.filter(p=>p.enabled&&(p.purpose??'video')==='video'&&p.modelFamily===selected.generation.modelFamily&&p.mode===selected.generation.mode&&p.workflowPath):[];

  return <Page title="Shot workshop" subtitle="Every shot is a reproducible local generation spec: continuity assets + direction + workflow + parameters." actions={selected&&<div className="row"><button className="ghost" onClick={()=>moveWithinScene(-1)}>←</button><button className="ghost" onClick={()=>moveWithinScene(1)}>→</button><button className="ghost" onClick={duplicateShot}>Duplicate</button><button className="ghost danger" disabled={Boolean(keyframeBusy)} onClick={deleteShot}>Delete</button><button className="ghost" disabled={continuityBusy} onClick={reviewContinuity}>{continuityBusy?'Reviewing metadata…':'Metadata continuity review'}</button><button className="ghost" onClick={autoRoute}>Auto route model</button><button className="primary" title={!routeReady?'Validate/select a video workflow first. Runtime, workflow bytes and model identity are rechecked by the main process when queued.':undefined} disabled={!routeReady} onClick={queue}>Queue render</button></div>}>
    {sorted.length===0?<Empty>Create shots from Storyboard first.</Empty>:<div className="shot-workbench"><aside className="shot-list">{sorted.map(s=><button key={s.id} className={selected?.id===s.id?'active':''} onClick={()=>selectShot(s.id)}><span>{s.title}</span><small>{s.generation.modelFamily}</small><Pill>{s.status}</Pill></button>)}</aside>
    {selected&&<div className="shot-editor">
      {(startAsset||endAsset||latest)&&<Card title="Visual state" kicker="CURRENT TAKE"><div className="keyframe-preview-grid"><MediaPreview label="START" asset={startAsset}/><MediaPreview label="END" asset={endAsset}/></div>{latest?.mediaType==='video'&&<video className="latest-render" src={projectMediaUrl(projectRelativeOutput(project.rootPath,latest.path))} controls preload="metadata"/>}</Card>}
      {takes.length>0&&<Card title="Takes" kicker="SHOT HISTORY"><div className="take-list">{takes.map(take=><div className="take-card" key={take.id}><video src={projectMediaUrl(projectRelativeOutput(project.rootPath,take.path))} muted preload="metadata"/><div className="take-actions"><div><strong>{take.filename}</strong><small>{new Date(take.createdAt).toLocaleString()}</small></div><div className="row">{selected.latestRenderId===take.id?<Pill>preferred</Pill>:<button className="ghost" onClick={()=>{const message=takeUseConfirmationMessage(take,'preferred');if(message&&!window.confirm(message))return;mutate(s=>{s.latestRenderId=take.id;s.status='rendered';});}}>Use take</button>}<button className="mini" onClick={()=>window.cineforge.system.reveal(take.path)}>↗</button></div></div></div>)}</div></Card>}
      {continuityReview&&<Card title="Continuity supervisor" kicker="LOCAL REVIEW" actions={<button className="ghost" onClick={()=>setContinuityReview(undefined)}>Dismiss</button>}>{continuityReview.issues.length===0?<div className="preflight-ok">No concrete continuity issue found from the current shot context.</div>:<div className="review-issues">{continuityReview.issues.map((issue,i)=><div key={i}>• {issue}</div>)}</div>}{(continuityReview.suggestedContinuityNotes||continuityReview.promptAddendum)&&<div className="grid two review-suggestions"><div><span className="field-label">Suggested continuity notes</span><p>{continuityReview.suggestedContinuityNotes||'—'}</p><button className="ghost" onClick={()=>{try{const next=appendProjectText(selected.continuityNotes,continuityReview.suggestedContinuityNotes,100_000,'Continuity notes');mutate(s=>s.continuityNotes=next);}catch(error){setError(error instanceof Error?error.message:String(error));}}}>Append notes</button></div><div><span className="field-label">Prompt addendum</span><p>{continuityReview.promptAddendum||'—'}</p><button className="ghost" onClick={()=>{try{const next=appendProjectText(selected.prompt,continuityReview.promptAddendum,200_000,'Shot prompt');mutate(s=>s.prompt=next);}catch(error){setError(error instanceof Error?error.message:String(error));}}}>Append prompt</button></div></div>}</Card>}
      <Card title={selected.title} kicker="DIRECTING"><div className="form-grid two-col"><label>Shot title<input value={selected.title} onChange={e=>mutate(s=>s.title=e.target.value)}/></label><label>Camera<input value={selected.camera} onChange={e=>mutate(s=>s.camera=e.target.value)}/></label></div><label>Visual prompt<textarea value={selected.prompt} onChange={e=>mutate(s=>s.prompt=e.target.value)}/></label><div className="form-grid two-col"><label>Action<textarea className="short" value={selected.action} onChange={e=>mutate(s=>s.action=e.target.value)}/></label><label>Dialogue / sound<textarea className="short" value={selected.dialogue} onChange={e=>mutate(s=>s.dialogue=e.target.value)}/></label></div><label>Continuity notes<textarea className="short" value={selected.continuityNotes} onChange={e=>mutate(s=>s.continuityNotes=e.target.value)}/></label></Card>
      <Card title="Drag assets onto this shot" kicker="ASSET DOCK"><div className="asset-dock">{project.assets.length===0?<Empty>Import characters, locations, props, frames, video or audio in Assets first.</Empty>:project.assets.map(asset=><button key={asset.id} type="button" className="draggable-asset" draggable onDragStart={event=>{event.dataTransfer.effectAllowed='copy';event.dataTransfer.setData('application/x-cineforge-asset',asset.id);}}>{['image','reference','keyframe','character','location','prop','wardrobe'].includes(asset.kind)?<img src={projectMediaUrl(asset.projectPath)} alt=""/>:<span className="asset-drag-icon">{asset.kind==='audio'?'♪':'▶'}</span>}<span><strong>{asset.name}</strong><small>{asset.kind}</small></span></button>)}</div></Card>
      <Card title="Continuity assets" kicker="IDENTITY / WORLD">
        <div className="drop-grid">
          <DropZone label="Characters · max 4" onDrop={e=>dropAsset(e,'character')}><MultiAssetSelect label="Characters" values={selected.characterAssetIds} assets={project.assets.filter(a=>a.kind==='character')} onChange={ids=>mutate(s=>s.characterAssetIds=ids)} max={4}/></DropZone>
          <DropZone label="Location" onDrop={e=>dropAsset(e,'location')}><AssetSelect label="Location" value={selected.locationAssetId} assets={project.assets.filter(a=>a.kind==='location')} onChange={v=>mutate(s=>s.locationAssetId=v||undefined)}/></DropZone>
          <DropZone label="Visual references · max 4" onDrop={e=>dropAsset(e,'reference')}><MultiAssetSelect label="Generic visual references" values={selected.referenceAssetIds??[]} assets={project.assets.filter(a=>a.kind==='reference')} onChange={ids=>mutate(s=>s.referenceAssetIds=ids)} max={4}/></DropZone>
          <DropZone label="Props / wardrobe · max 2" onDrop={e=>dropAsset(e,'prop')}><MultiAssetSelect label="Props / wardrobe refs" values={selected.propAssetIds} assets={project.assets.filter(a=>['prop','wardrobe'].includes(a.kind))} onChange={ids=>mutate(s=>s.propAssetIds=ids)} max={2}/></DropZone>
        </div>
      </Card>
      <Card title="Generation" kicker="MODEL ROUTING"><div className={`studio-route-status ${routeReady?'ready':route?'warn':'bad'}`}><span>VIDEO ROUTE</span><strong>{route?.name||'No enabled matching workflow'}</strong><small>{routeIssue||'profile validated · runtime/files rechecked on queue'}</small></div><div className="form-grid three-col"><label>Model<select value={selected.generation.modelFamily} onChange={e=>changeModel(e.target.value as ModelFamily)}>{MODELS.map(m=><option key={m}>{m}</option>)}</select></label><label>Mode<select value={selected.generation.mode} onChange={e=>mutate(s=>{s.generation.mode=e.target.value as GenerationMode;s.generation.workflowProfileId=undefined;})}>{MODES.map(m=><option key={m}>{m}</option>)}</select></label><label>Quality<select value={selected.generation.quality} onChange={e=>mutate(s=>s.generation.quality=e.target.value as QualityIntent)}>{QUALITIES.map(q=><option key={q}>{q}</option>)}</select></label></div><div className="form-grid two-col"><label>Workflow profile<select value={selected.generation.workflowProfileId||''} onChange={e=>mutate(s=>s.generation.workflowProfileId=e.target.value||undefined)}><option value="">Auto: validated matching route</option>{matchingProfiles.map(p=><option key={p.id} value={p.id} disabled={p.validation?.structuralStatus!=='valid'}>{p.name} · {p.validation?.structuralStatus||'unvalidated'}</option>)}</select></label><label className="check"><input type="checkbox" checked={selected.generation.includeAudio} onChange={e=>mutate(s=>s.generation.includeAudio=e.target.checked)}/>Generate / preserve audio where workflow supports it</label></div><div className="form-grid six-col"><Num label="Width" value={selected.generation.width} set={v=>mutate(s=>s.generation.width=v)}/><Num label="Height" value={selected.generation.height} set={v=>mutate(s=>s.generation.height=v)}/><Num label="Frames" value={selected.generation.frames} set={v=>mutate(s=>s.generation.frames=v)}/><Num label="FPS" value={selected.generation.fps} set={v=>mutate(s=>s.generation.fps=v)}/><Num label="Steps" value={selected.generation.steps||0} set={v=>mutate(s=>s.generation.steps=v)}/><Num label="CFG" value={selected.generation.cfg||0} step={0.1} set={v=>mutate(s=>s.generation.cfg=v)}/></div><label>Seed<input type="number" value={selected.generation.seed} onChange={e=>mutate(s=>s.generation.seed=Number(e.target.value))}/></label><label>Negative prompt<textarea className="short" value={selected.generation.negativePrompt} onChange={e=>mutate(s=>s.generation.negativePrompt=e.target.value)}/></label></Card>
      <Card title="Keyframes & motion references" kicker="SHOT CONTROL" actions={<div className="row"><select className="compact-select" value={activeKeyframeProfileId} onChange={e=>setKeyframeProfileId(e.target.value)}><option value="">Image workflow…</option>{imageProfiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="ghost" disabled={Boolean(keyframeBusy)} onClick={()=>generateKeyframe('start')}>{keyframeBusy==='start'?'Generating…':'Generate start'}</button><button className="ghost" disabled={Boolean(keyframeBusy)} onClick={()=>generateKeyframe('end')}>{keyframeBusy==='end'?'Generating…':'Generate end'}</button>{keyframeBusy&&<button className="ghost danger" onClick={cancelKeyframe}>Cancel</button>}</div>}><div className="row continuity-actions"><button className="ghost" onClick={chainPreviousEnd}>← Use previous final</button><button className="ghost" onClick={propagateEnd}>Use final for next →</button></div><div className="drop-grid two"><DropZone label="Start frame" onDrop={e=>dropAsset(e,'start')}><AssetSelect label="Start frame" value={selected.startFrameAssetId} assets={project.assets.filter(a=>['image','reference','keyframe','character','location'].includes(a.kind))} onChange={v=>mutate(s=>s.startFrameAssetId=v||undefined)}/></DropZone><DropZone label="End frame" onDrop={e=>dropAsset(e,'end')}><AssetSelect label="End frame" value={selected.endFrameAssetId} assets={project.assets.filter(a=>['image','reference','keyframe'].includes(a.kind))} onChange={v=>mutate(s=>s.endFrameAssetId=v||undefined)}/></DropZone><DropZone label="Motion / reference video" onDrop={e=>dropAsset(e,'video')}><AssetSelect label="Motion / reference video" value={selected.referenceVideoAssetId} assets={project.assets.filter(a=>a.kind==='video')} onChange={v=>mutate(s=>s.referenceVideoAssetId=v||undefined)}/></DropZone><DropZone label="Input audio" onDrop={e=>dropAsset(e,'audio')}><AssetSelect label="Input audio" value={selected.audioAssetId} assets={project.assets.filter(a=>a.kind==='audio')} onChange={v=>mutate(s=>s.audioAssetId=v||undefined)}/></DropZone></div></Card>
    </div>}</div>}</Page>;
}
function Num({label,value,set,step=1}:{label:string;value:number;set(v:number):void;step?:number}){return <label>{label}<input type="number" step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>;}
function AssetSelect({label,value,assets,onChange}:{label:string;value?:string;assets:Array<{id:string;name:string;kind:string}>;onChange(v:string):void}){return <label>{label}<select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">None</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name} · {a.kind}</option>)}</select></label>;}
function MultiAssetSelect({label,values,assets,onChange,max}:{label:string;values:string[];assets:Asset[];onChange(ids:string[]):void;max:number}){const toggle=(id:string)=>{if(values.includes(id))onChange(values.filter(x=>x!==id));else if(values.length<max)onChange([...values,id]);};return <div className="multi-assets"><span className="field-label">{label} <small>{values.length}/{max}</small></span><div className="asset-choice-row">{assets.length===0?<em>No matching assets imported.</em>:assets.map(a=><button key={a.id} type="button" className={values.includes(a.id)?'selected':''} onClick={()=>toggle(a.id)}>{a.name}</button>)}</div></div>;}
function MediaPreview({label,asset}:{label:string;asset?:Asset}){return <div className="keyframe-preview"><span>{label}</span>{asset?<img src={projectMediaUrl(asset.projectPath)} alt={asset.name}/>:<div>NO FRAME</div>}</div>;}
function projectRelativeOutput(root:string,absolute:string):string{const normalizedRoot=root.replace(/\\/g,'/').replace(/\/$/,'');const normalizedAbsolute=absolute.replace(/\\/g,'/');return normalizedAbsolute.startsWith(`${normalizedRoot}/`)?normalizedAbsolute.slice(normalizedRoot.length+1):normalizedAbsolute;}

function DropZone({label,onDrop,children}:{label:string;onDrop:(event:DragEvent<HTMLElement>)=>void;children:ReactNode}){return <section className="asset-drop-zone" onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';}} onDrop={onDrop}><span className="drop-zone-label">{label} · drop here</span>{children}</section>;}
